### ISSUE TITLE
Default values for `supervised` params `loss` and `bucket` are out of sync with C++ documentation

### ISSUE THREAD

**Issue by jeffkpayne** [salestock/fastText.py#100]
According to the docs for the fastText C++ library/tool, the `loss` param defaults to `'ns'` and the `bucket` param defaults to `2000000`, not `'softmax'` and `0`.

**Comment by jeffkpayne** [comment]
Hm, maybe it's that the defaults used in the Python module itself should be changed to match the ones in the fastText C++ library or command line executable.  When I leave out the `bucket` param in a call to `fasttext.supervised()`, I get a process-terminating exception.  For instance, here's an example in an `ipython` console:

```
In [1]: import fasttext

In [2]:     classifier = fasttext.supervised(
   ...:         input_file='train-small.txt',
   ...:         output='model',
   ...:         dim=10,
   ...:         lr=0.1,
   ...:         word_ngrams=2,
   ...:         min_count=1,
   ...:         bucket=0,
   ...:         epoch=5,
   ...:         thread=8)
fish: 'ipython' terminated by signal SIGFPE (Floating point exception)
```

So, the default value of `0` used by the Python module itself is causing the FPE.  If I set the `bucket` param to any other value, there is no exception.

**Comment by pyk** [comment]
Hi @jeffkpayne, thanks for the report!

I will look into this.

**Comment by pyk** [comment]
It seems that the C++ docs is outdated, here the default params in the C++:

```
lr 0.1
dim 100
ws 5
epoch 5
minCount 1
neg 5
wordNgrams 1
loss softmax
bucket 0
minn 0
maxn 0
thread 12
lrUpdateRate 100
t 0.0001
label __label__
```

Relevant code: https://github.com/facebookresearch/fastText/blob/master/src/args.cc#L43

FYI, we have run automated test for this https://github.com/salestock/fastText.py/blob/master/test/classifier_test.py#L137
to make sure that the default params is correct.

**Comment by jeffkpayne** [comment]
Thanks for the update!  Just noticed that the usage message spit out by the cli `fasttext supervised` is still incorrect.  Closing this and opening an issue over there.
