### ISSUE TITLE
Model loading with multiple processes ?

### ISSUE THREAD

**Issue by spate141** [salestock/fastText.py#109]
How to load fasttext models with multiple threads? Currently library is just using one process to load model and its taking too much time to load multiple models

**Comment by jeffkpayne** [comment]
@spate141  The `fastText` C++ lib _predict_ functionality is thread safe as of this commit, https://github.com/facebookresearch/fastText/commit/4528a72e783ee14462fc721dc3fe3d46a869ca08.  I'm using it in a multi-threaded way, by simply creating a classifier object with `fasttext.load_model()` and using the returned object in multiple threads.
