### ISSUE TITLE
Import error in Python 2.7 after installing

### ISSUE THREAD

**Issue by kskrishnasangeeth** [salestock/fastText.py#114]
- Getting the below error while trying to import fasttext

`ImportError: /home/<name>/anaconda2/envs/dev/lib/python2.7/site-packages/fasttext/fasttext.so: undefined symbol: _ZTVNSt7_E`

**Comment by pyk** [comment]
```
fasttext.so: undefined symbol: _ZTVNSt7_E
```

This is happen because `fasttext` is not compiled successfully or problem in the `anaconda` stuff #88. 

Can you try reinstall it again?

```
pip install -U fasttext
```
