### ISSUE TITLE
Loading multiple supervised classification models

### ISSUE THREAD

**Issue by spate141** [salestock/fastText.py#119]
I have 20 supervised classification models created with `fastText supervised`, each of with size of 1GB each. I am thinking about If I can compress/convert those .bin files in some way so that I can load all models at a same time quickly and use them to classify new data. Any thoughts?

**Comment by pyk** [comment]
One of the solution will be to deploy each model as a service and run independently across your cluster. For the inference step, you can do 20 requests to 20 services at the same time instead of sequentially.

**Comment by spate141** [comment]
Yes, I am planning to do this. I was wondering more about squeezing/converting these models in a certain way where I can load all of them in same machine, maybe using less memory. Anyway, some news on fastText.zip; They may open source the library hopefully by end of this week!
