### ISSUE TITLE
Load Model Error : Cannot load botModule/sentenceProcessing/vectorizer/model/wiki.fr.bin due to C++ extension failed to allocate the memory

### ISSUE THREAD

**Issue by Youyoun** [salestock/fastText.py#125]
Hey ,

I am trying to Load the wiki.fr.bin model in an ubuntu server 16.04 LTS 64 bit with 32G of memory, and I get the following error : 

```
Traceback (most recent call last):
  File "fasttext/fasttext.pyx", line 152, in fasttext.fasttext.load_model (fasttext/fasttext.cpp:4234)
RuntimeError: vector::_M_default_append

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/csdty/chatbot/botModule/sentenceProcessing/vectorizer/flaskVectorizer.py", line 6, in <module>
    v.loadModel()
  File "/home/csdty/chatbot/botModule/sentenceProcessing/vectorizer/vectorizer.py", line 13, in loadModel
    self.__classifier__ = fasttext.load_model(self.__model__)
  File "fasttext/fasttext.pyx", line 154, in fasttext.fasttext.load_model (fasttext/fasttext.cpp:4292)
Exception: fastText: Cannot load botModule/sentenceProcessing/vectorizer/model/wiki.fr.bin due to C++ extension failed to allocate the memory
```

The program works perfectly on my Mac OS with 8G of ram, but when I tried it on this machine, I get this error.

The Machine has 31G of free memory, the error happens instantly (as if the program just starts).
I'm running the program with Python 3.5.2, fasttext version is (0.8.3) 

This is what I get when I run : 
```
$ free -mh
              total        used        free      shared  buff/cache   available
Mem:            31G        270M         23G        9.0M        7.4G         30G
Swap:           15G          0B         15G
```

Thanks !

**Comment by srdadian** [comment]
Hi, 
I've had the same issues with small models I generated with the last fasttext update. It's not a memory issue: my old wiki.en model runs perfectly whereas my 150MB new model gives me your error. 
If we look at this python wrapper commits, it has not been updated for 3 months whereas they updated fasttext 14 days ago. I believe the question is: will the wrapper be updated soon? 
Thanks for the wrapper btw it's great with the old models.

**Comment by Youyoun** [comment]
Hey,
Thanks for your answer ! 
I just used scp to copy the model I had on my mac to the new machine (the one that worked on my mac which i downloaded before the update), and it works perfectly ! \o/

**Comment by wangyizhen** [comment]
## Firstly, just clone from the github.  and complie the fasttext (C++ version) from the cpp folders that have been cloned
git clone https://github.com/salestock/fastText.py.git
cd fastText
python setup.py install
### then, you will installed fasttext python package success.
### Finally , just to compile the fasttext c++ source code.
cd fasttext/cpp
make
you will compile success.

**Comment by appleyuchi** [comment]
no use at all on the above comments

**Comment by Emixam23** [comment]
Hi,

Any update on it?
