### ISSUE TITLE
Difficulty in compiling

### ISSUE THREAD

**Issue by sagnikbanerjee15** [salestock/fastText.py#127]
I am trying to compile by running the 'make' command. I keep running into the following error.

make
c++ -pthread -std=c++0x -O3 -funroll-loops -c src/args.cc
In file included from /opt/rit/app/gcc/6.2.0/include/c++/6.2.0/x86_64-pc-linux-gnu/bits/c++config.h:495:0,
                 from /opt/rit/app/gcc/6.2.0/include/c++/6.2.0/iosfwd:38,
                 from /opt/rit/app/gcc/6.2.0/include/c++/6.2.0/ios:38,
                 from /opt/rit/app/gcc/6.2.0/include/c++/6.2.0/istream:38,
                 from src/args.h:13,
                 from src/args.cc:10:
/opt/rit/app/gcc/6.2.0/include/c++/6.2.0/x86_64-pc-linux-gnu/bits/os_defines.h:39:22: fatal error: features.h: No such file or directory
 #include <features.h>
                      ^
compilation terminated.
make: *** [args.o] Error 1

Please tell me how to get around to correcting it. 

Thank you.

**Comment by pyk** [comment]
Hi @sagnikbanerjee15,

have you install the `build-essential` ?

**Comment by sagnikbanerjee15** [comment]
Thank you I have figured out another way to fix the problem

**Comment by pyk** [comment]
@sagnikbanerjee15 Nice!

Please share your solution here, might be useful for others. I will close this issue as fixed.
