### ISSUE TITLE
Nan Result with Classifier.test

### ISSUE THREAD

**Issue by vyraun** [salestock/fastText.py#132]
Hi

Running the example from here: https://github.com/miguelgfierro/sciblog_support/blob/master/Intro_to_NLP_with_fastText/Intro_to_NLP.ipynb

for the following code, I get the results:

result = classifier.test(test_file_clean)
print('P@1:', result.precision)
print('R@1:', result.recall)
print ('Number of examples:', result.nexamples)

P@1: nan
R@1: nan
Number of examples: 0

Any guess how to resolve the error? Thanks. The Input (test_file_clean) is a csv file.

Environment: Conda on Windows, Python 3.5.

**Comment by aylliote** [comment]
I reported the exact same issue in https://github.com/facebookresearch/fastText/issues/233
So if anyone has an answer i'm interested aswell

**Comment by datalee** [comment]
i face the same issues

**Comment by chuangys** [comment]
Same issue

**Comment by ShenMinXu** [comment]
Same issue  in win7 python3.6

**Comment by boysmax** [comment]
same issue ,win7  python3.7

**Comment by yangtianyu92** [comment]
same issue win10 python3.6

**Comment by ShenMinXu** [comment]
problem solved ，fasttext may not  support win ，linux is ok
