### ISSUE TITLE
Add predict_proba for classifier

### ISSUE THREAD

**Issue by lampts** [salestock/fastText.py#24]
It could be great if we can have this feature. I see in c++ code, there is a way to get the max values out of softmax function. Could you implement it or I can pull a request?

**Comment by pyk** [comment]
@lampts feel free to send PR! 😄

**Comment by pyk** [comment]
Related PR https://github.com/facebookresearch/fastText/pull/47/files

**Comment by lampts** [comment]
Yes, it seems to be duplicated.

**Comment by spate141** [comment]
@pyk thers's new update in fastText for predict-prob!

**Comment by pyk** [comment]
@spate141 yup yup, already working on it 😄

**Comment by pyk** [comment]
implemented here #60

**Comment by pyk** [comment]
Oh ya, for the API we use:

```python
labels = classifier.predict_proba(texts, k=2)
```

simple as always 😄
