### ISSUE TITLE
PIP install problem

### ISSUE THREAD

**Issue by mccoya2** [salestock/fastText.py#37]
running python v2.7 (anaconda) on mac (10.11.6). Pip install fails with following error:

 In file included from fasttext/fasttext.cpp:310:
    fasttext/cpp/src/dictionary.h:16:10: fatal error: 'random' file not found
    #include <random>
             ^
    1 error generated.
    error: command 'gcc' failed with exit status 1

**Comment by pyk** [comment]
Hi @mccoya2 ! 

Please take a look at issue #32 to solve this problem

**Comment by mccoya2** [comment]
Thanks pyk! Compiled gcc 6 and it worked fine (takes a while). I followed instructions outlined at https://solarianprogrammer.com/2016/05/10/compiling-gcc-6-mac-os-x/
