### ISSUE TITLE
Issue installing it with pip

### ISSUE THREAD

**Issue by MatthiasRMS** [salestock/fastText.py#45]
I tried running:

`pip install fasttext`

and got this error:

  ```
In file included from fasttext/fasttext.cpp:310:
  fasttext/cpp/src/dictionary.h:16:10: fatal error: 'random' file not found
  #include <random>
           ^
  1 error generated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for fasttext
```

Any idea on how to fix this ?

**Comment by pyk** [comment]
hi @MatthiasRMS

Please take a look at #28 to solve this problem

**Comment by Peter-E-Lenz** [comment]
I'm having the same issue, 
`CC=/usr/bin/gcc-5.4 
pip install fasttext`
is resulting in the same error.

Curiously building a standalone instance of fasttext outside of pip does work with the same setup.

**Comment by pyk** [comment]
@MatthiasRMS is the solution works for you?

@Peter-E-Lenz can you give us the output from stderr ?

**Comment by Peter-E-Lenz** [comment]
`CC=/usr/bin/gcc-5.4

pip install fasttext 2>&1 >/dev/null | less`
results in

> Failed building wheel for fasttext
> Command "/Users/plenz/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/qk/v9kxv7sj5ls3k89gwk6615zm0000gt/T/pip-build-71A_LC/fasttext/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/qk/v9kxv7sj5ls3k89gwk6615zm0000gt/T/pip-BemSc7-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/qk/v9kxv7sj5ls3k89gwk6615zm0000gt/T/pip-build-71A_LC/fasttext/

**Comment by pyk** [comment]
> Failed building wheel for fasttext

@Peter-E-Lenz ahh, currently we don't upload the package in wheel distribution yet.

We will upload the wheel distribution ASAP

**Comment by spate141** [comment]
sudo port install gcc7
$ port select --list gcc
Available versions for gcc:
	mp-gcc7
	mp-llvm-gcc42
	none (active)
$ sudo port select --set gcc mp-gcc7
Password:
Selecting 'mp-gcc7' for 'gcc' succeeded. 'mp-gcc7' is now active.

pip install fasttext

**Comment by flybirp** [comment]
same error encountered, tried all the above comments, yet nothing changed

**Comment by pyk** [comment]
Hi @flybirp, can you give us the error output from your `pip install fasttext`?

Note that 📓  : currently we don't distribute the package in `wheel` format yet. So if you install the package in `wheel` format, it will error. Try to use the `egg` format

Related #47

**Comment by MatthiasRMS** [comment]
@pyk  thanks for your answer, I'll follow the solution today and let you know if it works out

**Comment by flybirp** [comment]
hi there:

Installing collected packages: fasttext
  Running setup.py install for fasttext ... error
    Complete output from command /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/72/mzywkdcd73l_9pd98pdgmw280000gn/T/pip-build-f12cdwfh/fasttext/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/72/mzywkdcd73l_9pd98pdgmw280000gn/T/pip-kzayzgpb-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-intel-3.5
    creating build/lib.macosx-10.6-intel-3.5/fasttext
    copying fasttext/__init__.py -> build/lib.macosx-10.6-intel-3.5/fasttext
    copying fasttext/model.py -> build/lib.macosx-10.6-intel-3.5/fasttext
    running build_ext
    building 'fasttext.fasttext' extension
    creating build/temp.macosx-10.6-intel-3.5
    creating build/temp.macosx-10.6-intel-3.5/fasttext
    creating build/temp.macosx-10.6-intel-3.5/fasttext/cpp
    creating build/temp.macosx-10.6-intel-3.5/fasttext/cpp/src
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c fasttext/fasttext.cpp -o build/temp.macosx-10.6-intel-3.5/fasttext/fasttext.o -pthread -funroll-loops -std=c++0x
    In file included from fasttext/fasttext.cpp:310:
    fasttext/cpp/src/dictionary.h:16:10: fatal error: 'random' file not found
    #include <random>
             ^
    1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1

    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/72/mzywkdcd73l_9pd98pdgmw280000gn/T/pip-build-f12cdwfh/fasttext/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/72/mzywkdcd73l_9pd98pdgmw280000gn/T/pip-kzayzgpb-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/72/mzywkdcd73l_9pd98pdgmw280000gn/T/pip-build-f12cdwfh/fasttext/

**Comment by flybirp** [comment]
by the way, I did install newer version of gcc with homebrew

**Comment by pyk** [comment]
@flybirp have you tried this?

```
CC=/path/to/your/latest-gcc-binary pip install fasttext
```

change the `/path/to/your/latest-gcc-binary` with the latest one

**Comment by flybirp** [comment]
yes, by trying this, will gives me a different error

Installing collected packages: fasttext
  Running setup.py install for fasttext ... error
    Complete output from command /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/72/mzywkdcd73l_9pd98pdgmw280000gn/T/pip-build-dxzsbtml/fasttext/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/72/mzywkdcd73l_9pd98pdgmw280000gn/T/pip-r3gt3sl3-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-intel-3.5
    creating build/lib.macosx-10.6-intel-3.5/fasttext
    copying fasttext/__init__.py -> build/lib.macosx-10.6-intel-3.5/fasttext
    copying fasttext/model.py -> build/lib.macosx-10.6-intel-3.5/fasttext
    running build_ext
    building 'fasttext.fasttext' extension
    creating build/temp.macosx-10.6-intel-3.5
    creating build/temp.macosx-10.6-intel-3.5/fasttext
    creating build/temp.macosx-10.6-intel-3.5/fasttext/cpp
    creating build/temp.macosx-10.6-intel-3.5/fasttext/cpp/src
    /usr/bin/gcc -fno-strict-aliasing -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c fasttext/fasttext.cpp -o build/temp.macosx-10.6-intel-3.5/fasttext/fasttext.o -pthread -funroll-loops -std=c++0x
    gcc: warning: x86_64 conflicts with i386 (arch flags ignored)
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    /usr/bin/gcc -fno-strict-aliasing -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c fasttext/interface.cc -o build/temp.macosx-10.6-intel-3.5/fasttext/interface.o -pthread -funroll-loops -std=c++0x
    gcc: warning: x86_64 conflicts with i386 (arch flags ignored)
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    In file included from fasttext/interface.cc:15:0:
    fasttext/cpp/src/fasttext.cc: In function 'void cbow(Dictionary&, Model&, const std::vector<int>&, double&, int32_t&)':
    fasttext/cpp/src/fasttext.cc:134:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int32_t w = 0; w < line.size(); w++) {
                           ~~^~~~~~~~~~~~~
    fasttext/cpp/src/fasttext.cc:138:41: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           if (c != 0 && w + c >= 0 && w + c < line.size()) {
                                       ~~~~~~^~~~~~~~~~~~~
    fasttext/cpp/src/fasttext.cc: In function 'void skipgram(Dictionary&, Model&, const std::vector<int>&, double&, int32_t&)':
    fasttext/cpp/src/fasttext.cc:152:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int32_t w = 0; w < line.size(); w++) {
                           ~~^~~~~~~~~~~~~
    fasttext/cpp/src/fasttext.cc:156:41: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           if (c != 0 && w + c >= 0 && w + c < line.size()) {
                                       ~~~~~~^~~~~~~~~~~~~
    fasttext/interface.cc: In function 'void trainWrapper(int, char**, int)':
    fasttext/interface.cc:192:39: warning: 'char* tmpnam(char*)' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of tmpnam(3), it is highly recommended that you use mkstemp(3) instead. [-Wdeprecated-declarations]
         std::string temp_file_name = std::tmpnam(nullptr);
                                           ^~~~~~
    In file included from /usr/include/wchar.h:90:0,
                     from /usr/local/Cellar/gcc6/6.1.0/include/c++/6.1.0/cwchar:44,
                     from /usr/local/Cellar/gcc6/6.1.0/include/c++/6.1.0/bits/postypes.h:40,
                     from /usr/local/Cellar/gcc6/6.1.0/include/c++/6.1.0/iosfwd:40,
                     from /usr/local/Cellar/gcc6/6.1.0/include/c++/6.1.0/ios:38,
                     from /usr/local/Cellar/gcc6/6.1.0/include/c++/6.1.0/ostream:38,
                     from /usr/local/Cellar/gcc6/6.1.0/include/c++/6.1.0/iostream:39,
                     from fasttext/interface.cc:2:
    /usr/include/stdio.h:276:7: note: declared here
     char *tmpnam(char *);
           ^~~~~~
    fasttext/interface.cc:192:53: warning: 'char* tmpnam(char*)' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of tmpnam(3), it is highly recommended that you use mkstemp(3) instead. [-Wdeprecated-declarations]
         std::string temp_file_name = std::tmpnam(nullptr);
                                                         ^
    In file included from /usr/include/wchar.h:90:0,
                     from /usr/local/Cellar/gcc6/6.1.0/include/c++/6.1.0/cwchar:44,
                     from /usr/local/Cellar/gcc6/6.1.0/include/c++/6.1.0/bits/postypes.h:40,
                     from /usr/local/Cellar/gcc6/6.1.0/include/c++/6.1.0/iosfwd:40,
                     from /usr/local/Cellar/gcc6/6.1.0/include/c++/6.1.0/ios:38,
                     from /usr/local/Cellar/gcc6/6.1.0/include/c++/6.1.0/ostream:38,
                     from /usr/local/Cellar/gcc6/6.1.0/include/c++/6.1.0/iostream:39,
                     from fasttext/interface.cc:2:
    /usr/include/stdio.h:276:7: note: declared here
     char *tmpnam(char *);
           ^~~~~~
    /usr/bin/gcc -fno-strict-aliasing -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c fasttext/cpp/src/args.cc -o build/temp.macosx-10.6-intel-3.5/fasttext/cpp/src/args.o -pthread -funroll-loops -std=c++0x
    gcc: warning: x86_64 conflicts with i386 (arch flags ignored)
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    /usr/bin/gcc -fno-strict-aliasing -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c fasttext/cpp/src/dictionary.cc -o build/temp.macosx-10.6-intel-3.5/fasttext/cpp/src/dictionary.o -pthread -funroll-loops -std=c++0x
    gcc: warning: x86_64 conflicts with i386 (arch flags ignored)
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    fasttext/cpp/src/dictionary.cc: In member function 'void Dictionary::computeNgrams(const string&, std::vector<int>&)':
    fasttext/cpp/src/dictionary.cc:129:52: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (size_t j = i, n = 1; j < word.size() && n <= args.maxn; n++) {
                                                      ~~^~~~~~~~~~~~
    fasttext/cpp/src/dictionary.cc:134:13: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           if (n >= args.minn) {
               ~~^~~~~~~~~~~~
    fasttext/cpp/src/dictionary.cc: In member function 'void Dictionary::initNgrams()':
    fasttext/cpp/src/dictionary.cc:143:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (size_t i = 0; i < size_; i++) {
                          ~~^~~~~~~
    fasttext/cpp/src/dictionary.cc: In member function 'void Dictionary::initTableDiscard()':
    fasttext/cpp/src/dictionary.cc:216:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (size_t i = 0; i < size_; i++) {
                          ~~^~~~~~~
    /usr/bin/gcc -fno-strict-aliasing -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c fasttext/cpp/src/matrix.cc -o build/temp.macosx-10.6-intel-3.5/fasttext/cpp/src/matrix.o -pthread -funroll-loops -std=c++0x
    gcc: warning: x86_64 conflicts with i386 (arch flags ignored)
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    /usr/bin/gcc -fno-strict-aliasing -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c fasttext/cpp/src/model.cc -o build/temp.macosx-10.6-intel-3.5/fasttext/cpp/src/model.o -pthread -funroll-loops -std=c++0x
    gcc: warning: x86_64 conflicts with i386 (arch flags ignored)
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    fasttext/cpp/src/model.cc: In member function 'real Model::hierarchicalSoftmax(int32_t)':
    fasttext/cpp/src/model.cc:71:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int32_t i = 0; i < pathToRoot.size(); i++) {
                           ~~^~~~~~~~~~~~~~~~~~~
    fasttext/cpp/src/model.cc: In member function 'void Model::findKBest(int32_t, std::vector<std::pair<float, int> >&)':
    fasttext/cpp/src/model.cc:127:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (heap.size() == k && output_[i] < heap.front().first) {
             ~~~~~~~~~~~~^~~~
    fasttext/cpp/src/model.cc:132:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (heap.size() > k) {
             ~~~~~~~~~~~~^~~
    fasttext/cpp/src/model.cc: In member function 'void Model::dfs(int32_t, int32_t, real, std::vector<std::pair<float, int> >&)':
    fasttext/cpp/src/model.cc:141:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if (heap.size() == k && score < heap.front().first) {
           ~~~~~~~~~~~~^~~~
    fasttext/cpp/src/model.cc:148:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (heap.size() > k) {
             ~~~~~~~~~~~~^~~
    /usr/bin/gcc -fno-strict-aliasing -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c fasttext/cpp/src/utils.cc -o build/temp.macosx-10.6-intel-3.5/fasttext/cpp/src/utils.o -pthread -funroll-loops -std=c++0x
    gcc: warning: x86_64 conflicts with i386 (arch flags ignored)
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    fasttext/cpp/src/utils.cc: In function 'void utils::seek(std::ifstream&, int64_t)':
    fasttext/cpp/src/utils.cc:72:10: warning: unused variable 'c' [-Wunused-variable]
         char c;
              ^
    /usr/bin/gcc -fno-strict-aliasing -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c fasttext/cpp/src/vector.cc -o build/temp.macosx-10.6-intel-3.5/fasttext/cpp/src/vector.o -pthread -funroll-loops -std=c++0x
    gcc: warning: x86_64 conflicts with i386 (arch flags ignored)
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    g++-4.2 -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -g build/temp.macosx-10.6-intel-3.5/fasttext/fasttext.o build/temp.macosx-10.6-intel-3.5/fasttext/interface.o build/temp.macosx-10.6-intel-3.5/fasttext/cpp/src/args.o build/temp.macosx-10.6-intel-3.5/fasttext/cpp/src/dictionary.o build/temp.macosx-10.6-intel-3.5/fasttext/cpp/src/matrix.o build/temp.macosx-10.6-intel-3.5/fasttext/cpp/src/model.o build/temp.macosx-10.6-intel-3.5/fasttext/cpp/src/utils.o build/temp.macosx-10.6-intel-3.5/fasttext/cpp/src/vector.o -o build/lib.macosx-10.6-intel-3.5/fasttext/fasttext.cpython-35m-darwin.so
    unable to execute 'g++-4.2': No such file or directory
    error: command 'g++-4.2' failed with exit status 1

    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/72/mzywkdcd73l_9pd98pdgmw280000gn/T/pip-build-dxzsbtml/fasttext/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/72/mzywkdcd73l_9pd98pdgmw280000gn/T/pip-r3gt3sl3-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/72/mzywkdcd73l_9pd98pdgmw280000gn/T/pip-build-dxzsbtml/fasttext/

**Comment by pyk** [comment]
> unable to execute 'g++-4.2': No such file or directory
> error: command 'g++-4.2' failed with exit status 1

@flybirp now the problem is `g++-4.2` is not available on your system. 

Strange, it should work with: `env CC=/path/to/your/latest-gcc-binary pip install fasttext`

**Comment by londonm** [comment]
Also running into the "Failed building wheel issue"  

C:\Users\hiddenuser\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python
\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\python27\include -I
c:\python27\PC /Tpfasttext/fasttext.cpp /Fobuild\temp.win32-2.7\Release\fasttext
/fasttext.obj -pthread -funroll-loops -std=c++0x
  cl : Command line warning D9002 : ignoring unknown option '-pthread'
  cl : Command line warning D9002 : ignoring unknown option '-funroll-loops'
  cl : Command line warning D9002 : ignoring unknown option '-std=c++0x'
  fasttext.cpp
  C:\Users\hiddenuser\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python
\9.0\VC\Include\xlocale(342) : warning C4530: C++ exception handler used, but un
wind semantics are not enabled. Specify /EHsc
  c:\users\hiddenuser\appdata\local\temp\17\pip-build-ucwunz\fasttext\fasttext\cpp/
src/utils.h(31) : error C2146: syntax error : missing ';' before identifier 'siz
e'
  c:\users\hiddenuser\appdata\local\temp\17\pip-build-ucwunz\fasttext\fasttext\cpp/
src/utils.h(31) : error C4430: missing type specifier - int assumed. Note: C++ d
oes not support default-int
  c:\users\hiddenuser\appdata\local\temp\17\pip-build-ucwunz\fasttext\fasttext\cpp/
src/utils.h(31) : error C4430: missing type specifier - int assumed. Note: C++ d
oes not support default-int
  c:\users\hiddenuser\appdata\local\temp\17\pip-build-ucwunz\fasttext\fasttext\cpp/
src/utils.h(32) : error C2061: syntax error : identifier 'int64_t'
  fasttext/fasttext.cpp(308) : fatal error C1083: Cannot open include file: 'std
int.h': No such file or directory
  error: command 'C:\\Users\\hiddenuser\\AppData\\Local\\Programs\\Common\\Microsof
t\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for fasttext
  Running setup.py clean for fasttext
Failed to build fasttext

**Comment by pyk** [comment]
Hi @londonm, we don't distribute this package in `wheel` format yet

**Comment by pyk** [comment]
Closed, since the OP already install the fasttext successfully #54
