### ISSUE TITLE
Issue with labels recognition

### ISSUE THREAD

**Issue by lcorbel** [salestock/fastText.py#52]
Hi,

There seems to be an issue when training a classifier on an input txt file. The labels are not recognized even though they have the right prefix in front of them.

I tried with both the default  '\__label__' prefix and custom prefix and both did not work.

Good luck in your work, it seems promising ! :)

**Comment by pyk** [comment]
@lcorbel can you give us the example your data? Will try to reproduce it. Especially on lines that doesn't recognised as label
