### ISSUE TITLE
Issues with latest update ?

### ISSUE THREAD

**Issue by MatthiasRMS** [salestock/fastText.py#54]
Hi,

I've updated the package and now, when training a classifier:
```
import fasttext
classifier = fasttext.supervised('train.txt', 'model')
```

 I get this:

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

Is it coming from my environment or is it due to the latest update ?

**Comment by pyk** [comment]
Hi @MatthiasRMS , `std::bad_alloc` means the C++ extension cannot allocate memory to the heap. Please check the size of `model.bin` and make sure that you have enough memory to load it
