### ISSUE TITLE
Predict Performance

### ISSUE THREAD

**Issue by elmar-haussmann** [salestock/fastText.py#59]
The performance of `classifier.predict` is extremely bad at the moment. This is because for each call `FastTextModel::classifierPredict` instantiates `Model model(_input_matrix, _output_matrix, dim, args.lr, 1);`, which in turn recomputes the binary tree for hierarchical softmax. In my experiments, this took roughly a second for each call, but it depends on the size of the dictionary.

One solution would be to make the model a member of FastTextModel.

**Comment by minimaxir** [comment]
Hitting similar performance issues (1 sec/call on a large dictionary) with `classifier.predict`.

**Comment by pyk** [comment]
@elmar-haussmann @minimaxir yup yup, and it seems the latest version of fastText already store the model inside `FastText` class https://github.com/facebookresearch/fastText/blob/c5eda6041e9274c672196d1f56bcb66e0682a18a/src/fasttext.h#L24-L32

So we don't need to instantiates the `Model` in `classifier.predict` anymore, I will ship this change together with #24

**Comment by pyk** [comment]
solved by #60 and `classifier.predict` performance is improved at fastText.py v0.7.3 release
