### ISSUE TITLE
fastText 0.7.3 pip install issue

### ISSUE THREAD

**Issue by spate141** [salestock/fastText.py#61]
> CC=/opt/local/bin/gcc pip install fasttext

`gcc: error: unrecognized command line option '-stdlib=libc++'
  error: command '/opt/local/bin/gcc' failed with exit status 1`

**Comment by pyk** [comment]
Are you using OSX?

**Comment by spate141** [comment]
Yes, OSX. and I already tried this option also,
https://github.com/salestock/fastText.py/issues/45#issuecomment-241822960

**Comment by pyk** [comment]
hmm it [seems](http://stackoverflow.com/questions/24419832/unrecognized-command-line-option-stdlib-libc-with-macports-gcc48) that  `-stdlib=libc++` is for `clang`. Not for `gcc`

**Comment by pyk** [comment]
The OSX build is fixed by @xiamx on #55, I think it should work without `CC=/opt/local/bin/gcc`

**Comment by spate141** [comment]
> CC=/usr/bin/clang pip install fasttext

..and its solved! Thanks 🙂

**Comment by pyk** [comment]
yup yup @spate141 👍

**Comment by ben0it8** [comment]
can you please share the exact solution? I ran into the same error.
