### ISSUE TITLE
skipgram is unknown

### ISSUE THREAD

**Issue by mbaniasad** [salestock/fastText.py#66]
i'm getting this error 
attributeError: 'module' object has no attribute 'skipgram'

```
import fasttext

# Skipgram model
model = fasttext.skipgram(datasetName + "/fastTextFomattrain.txt", 'model') # error here
print model.words   # list of words in dictionary
```

**Comment by pyk** [comment]
Hi @mbaniasad , 

The `skipgram` is defined [here](https://github.com/salestock/fastText.py/blob/master/fasttext/__init__.py#L1) it should be callable (tested [here](https://github.com/salestock/fastText.py/blob/master/test/skipgram_test.py#L56)).

Can you give us the output of `fasttext.__VERSION__` ?

**Comment by mbaniasad** [comment]
seems the error was due to the fact that my test filename was fasttext   
tried it in another dir with python shell and it seemed working  
so i renamed the file and now it's getting over this error. thanks
