### ISSUE TITLE
predict-proba return empty results

### ISSUE THREAD

**Issue by jinzhang-zj** [salestock/fastText.py#72]
I ran the predict-proba over 60k test samples, and get a probability tuple inside a list for most of the samples, however, a small fraction of the samples return an empty list, did anyone have the same issue?

I ran the fastText binary version it runs normally and return probability for all samples

**Comment by pyk** [comment]
Hi @jinzhang-zj,

Sorry, I can't reproduce your issue. I have compare the output from `fasttext(1)` and `classifier.predict_proba`  and the result is the same. (Tested [here](https://github.com/salestock/fastText.py/blob/master/Makefile#L102) and [here](https://github.com/salestock/fastText.py/blob/master/test/classifier_test.py#L256))

Please make sure that you are running the same version of fasttext binary. fastText v0.7.6 is using fastText [602355a](https://github.com/facebookresearch/fastText/tree/602355a).

**Comment by jinzhang-zj** [comment]
Thanks for replying so promptly.

It looks my problem can be resolved if I keep the first comma right after the "__label__x", not sure it's the correct way of doing this but now it gives the same results as the binary version.
