### ISSUE TITLE
fasttext.cbow() 'input' param is system builtin

### ISSUE THREAD

**Issue by kn45** [salestock/fastText.py#80]
it seems that 'input' is system builtin, if passing value as: 
    cbow = fasttext.cbow(input='data',  output='model')
would cause error:
    File "fasttext/fasttext.pyx", line 247, in fasttext.fasttext.cbow (fasttext/fasttext.cpp:5795)
    TypeError: cbow() takes at least 2 positional arguments (0 given)

cbow = fasttext.cbow('data',  output='model') is ok.

**Comment by kn45** [comment]
ok, i found the param name should be input_file.

**Comment by pyk** [comment]
Thanks @kn45 for the report and PR #81, will merge the PR! 👍
