### ISSUE TITLE
out-of-vocabulary words in text classification

### ISSUE THREAD

**Issue by gnardari** [salestock/fastText.py#83]
When running Facebook Fasttext, the supervised classifier approximates vectors for out-of-vocabulary words but using the python interface for the same train/test dataset yields an empty list (word-vector is all zeroes). An easy way to test this is trying to classify a single unseen word. 

Is this the expected behaviour? 

I'm using Fasttext 0.7.6 with python 2.7.10

**Comment by pyk** [comment]
Hi @gnardari,
If you want to get the word vector from unseen words you can use `skipgram` or `cbow` model.

**Comment by gnardari** [comment]
Thanks for the reply.  I managed to get the word vectors for unseen words using the word2vec algorithms but I'm trying to feed this vectors  to the supervised classifier. Is there a built in way of doing this?

**Comment by pyk** [comment]
> I managed to get the word vectors for unseen words using the word2vec algorithms but I'm trying to feed this vectors to the supervised classifier. Is there a built in way of doing this?

No, currently not supported yet. However you can use `fasttext(1)` C++ directly and use `-pretrainedVectors` params

**Comment by pyk** [comment]
Follow up issue about pre-trained word vectors #85

**Comment by pyk** [comment]
pre-trained word vectors is now supported #93
