### ISSUE TITLE
Support pre-trained word vector for classifier

### ISSUE THREAD

**Issue by pyk** [salestock/fastText.py#85]
Implement `-pretrainedVectors` params

**Comment by catethos** [comment]
hi I am willing to help this but I am not familiar with cython, any pointer to which part of code should I read first?

**Comment by pyk** [comment]
Hi @catethos,

You can start from https://github.com/salestock/fastText.py/blob/master/fasttext/fasttext.pyx#L238 to get general idea of

```
fasttext.skipgram(...)
```
 how we use cython to pass and receive data from python to c++.

I recommend to read this docs first http://cython.readthedocs.io/en/latest/src/tutorial/cython_tutorial.html

**Comment by gggdomi** [comment]
Hi @pyk, @catethos,

I sent a PR enabling pretrainedVectors support. 
I have compared classifier performance with/without it. It makes a notable difference - especially when there is few training epochs - so I guess it is taking the pretained word vectors into account.

**Comment by pyk** [comment]
Thanks @gggdomi! Fixed by #93
