### ISSUE TITLE
Can not install fasttext.py in Linux Mint 18 Sarah

### ISSUE THREAD

**Issue by odgiv** [salestock/fastText.py#87]
Hello, I am getting an error saying as below when I try to install fasttext python package on my linux machine. Do you know how to fix this issue?

> cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
fasttext/fasttext.cpp:26:20: fatal error: Python.h: No such file or directory
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by pyk** [comment]
Hi @odgiv ,

> fasttext/fasttext.cpp:26:20: fatal error: Python.h: No such file or directory

You need to install `python-dev` package first on your linux machine

**Comment by odgiv** [comment]
Hi @pyk Thank you. It works now.

**Comment by pyk** [comment]
Nice 👍

**Comment by bilalbayasut** [comment]
@pyk hi bayu, how about If I have installed the python-dev and restart my machine, the error above still occurred ?
