### ISSUE TITLE
Installing fasttext with Anaconda

### ISSUE THREAD

**Issue by s-j** [salestock/fastText.py#88]
Hi, I have tried to install fastText.py on top of my Anaconda installation. `pip install fasttext` completes well, but the following fails:

```
$ python
Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fasttext
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/simonj/opt/anaconda3/lib/python3.5/site-packages/fasttext/__init__.py", line 1, in <module>
    from .fasttext import skipgram
ImportError: /home/simonj/opt/anaconda3/lib/python3.5/site-packages/fasttext/fasttext.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE
```

Could you please explain the error or what have I done wrong?

Thanks,
Simon

**Comment by pyk** [comment]
Hi @s-j,

```
ImportError: /home/simonj/opt/anaconda3/lib/python3.5/site-packages/fasttext/fasttext.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE
```

it seems that the C++ extension is compiled unsuccessfully. 

Please run `pip install -U fasttext` and make sure that the fasttext version is `0.8.0`

**Comment by s-j** [comment]
Hi Bayu, thanks for a quick response. Have tried `pip install -U fasttext --no-cache-dir --no-deps --force-reinstall` a couple of times without luck. I have downloaded and compiled the original code and it works like a charm. The machine here is runs Ubuntu 16.04 with Anaconda3 4.2.9, could that be of a problem?

Installation on my macbook laptop (also running the same version of anaconda) works without problems.

**Comment by yenchaos** [comment]
Hi @s-j , I encountered the same issue on my desktop which also runs Ubuntu 16.04 with Anaconda3 4.2.0. Mac is good. I realized that my aws instance (Ubuntu 14.04) runs well with Anaconda3 4.1.1, so I changed the Anaconda3 version to 4.1.1. Finally it works, but I don't know the reason.

**Comment by s-j** [comment]
No longer required, seems to work just fine.

**Comment by koenvanderveen** [comment]
Hi, 
I am having exactly the same problem (but with python 2.7). Can you tell me how you fixed this?

**Comment by bkj** [comment]
I'm having the same problem -- any ideas?

**Comment by geovedi** [comment]
for Anaconda3 users, try install/update `libgcc`: `conda install libgcc`

**Comment by rdoume** [comment]
@geovedi  Thanks, that did the trick for me

**Comment by markup1** [comment]
Hi @s-j,
I have the same problem with it。Finally ,I soveled it。

1. My working environment is ubuntu 16.04LTS& Anaconda4.4.0.
2.  ubuntu 16.04  defaul translater is gcc-5.4 and g ++ - 5.4。so，when I use `pip install fasttext`, it has the problem like you. I think it is the translater version fault。then I find this issues. But not  working。
3. **So , I reinstall the lower translater gcc-4.7 and g ++ - 4.7**，It is working.
4. **command code**
```
# Configuration gcc-4.7
sudo apt-get install gcc-4.7 gcc-4.7-multilib g++-4.7 g++-4.7-multilib
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 50
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 40
# choose 4.7
sudo update-alternatives --config gcc

# Configuration g++-4.7
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.7 50
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 40
# choose 4.7
sudo update-alternatives --config g++
```

**Comment by nov1160** [comment]
@markup1, your solution works for me too.

**Comment by BigNewbiePlus** [comment]
@geovedi awesome advice

**Comment by 01joy** [comment]
You should **exit** your conda env to run @geovedi 's code!

**Comment by liliangjie91** [comment]
> for Anaconda3 users, try install/update `libgcc`: `conda install libgcc`

also works for Anaconda2 users
