### ISSUE TITLE
load_model not working

### ISSUE THREAD

**Issue by dmartincc** [salestock/fastText.py#98]
For the code attached, I got this message "'module' object has no attribute 'load_model'",
I tried uninstalling and reinstalling again Cython and fasttext. Any clue, why might this happen?

`
import fasttext as ft
`
`
model = ft.load_model('model.bin')
`

**Comment by pyk** [comment]
Hi @dmartincc,

Make sure there are no file named `fasttext.{py,pyc}` in the current directory

**Comment by dmartincc** [comment]
@pyk that was the problem, cheers.

**Comment by ExceptionK** [comment]
When I use this code:  
def __init__(self, model_file='model/lid.176.ftz', language_code_file='language_code.json'):
        self.model = ft.load_model(model_file)
I will be informed:   
self.model = ft.load_model(model_file)
AttributeError: module 'fastText' has no attribute 'load_model'
Why might this happen?
