### ISSUE TITLE
prediction: blanks [[],[],[],[]]

### ISSUE THREAD

**Issue by eloiup** [salestock/fastText.py#99]
Hi.

Trying to use it on:
ipython notebook (anaconda) python 2.7
linux

simple example not working not sure what i am doing wrong.

txt file:

```
__label__WithNumbers J2VIEW5BJU
__label__NoNumbers AXUCXWNPCV
__label__NoNumbers DDUVWVPCJW
__label__WithNumbers 99W5K7EO91
__label__NoNumbers YPEVGZGEPW
__label__WithNumbers 4Z3KVHIW1P
....
````

```
classifier = fasttext.supervised(
                input_file='file.txt',
                output='model',
                word_ngrams=2
           )
```

```
[in]: classifier.predict('KFAOEKFEAIJFAE')  
[out]: [[], [], [], [], [], [], [], [], [], [], [], [], [], []]
```

any ideas whats going on or how to fix it? thx

**Comment by pyk** [comment]
Hi @eloiup,

Your simple example only contains a one-word only. By default, a supervised model in the fasttext expect the following:

1. `ws=5` the context window should be at least `5`. Your training text is doesn't have any context at all, only one word.
2. `min_count=5` this is a minimal number of word occurences. your dataset is unique, each word appear only once.

The information available here: https://github.com/salestock/fastText.py#skipgram-model

I hope it helps
